flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/reflex-frp/reflex-dom-contrib.git
    commit: d6c744928c81bdb0cd3141f05f7529dc0dae5327
extra-deps:
- ref-tf-0.4.0.1
- reflex-0.4.0
- reflex-dom-0.3
resolver: lts-6.4
