flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-0.11.2.0
- http2-1.6.0
- servant-0.7.1
- servant-blaze-0.7.1
- servant-server-0.7.1
- text-1.2.2.1
- wai-extra-3.0.15.2
- warp-3.2.6
resolver: lts-5.17
